[licenses]
allow = ["MIT", "Apache-2.0", "CC0-1.0", "Unicode-3.0", "ISC", "MPL-2.0"]

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
unknown-registry = "deny"
unknown-git = "deny"
