[licenses]
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "BSD-2-Clause", "ISC", "Zlib"]

deny = [
  "GPL-3.0",
  "GPL-2.0",
  "LGPL-3.0",
  "LGPL-2.1",
  "AGPL-3.0",
  "MPL-2.0",
  "Unlicense",
]
allow-osi-fsf-free = "neither"

[bans]
multiple-versions = "deny"

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
